function mouseClicked(){
    if(stage.question<questions.length-1){
        if(mouseX>50*width/800&&mouseX<350*width/800&&mouseY>250*height/550&&mouseY<350*height/550&&!transition.trigger){
            transition.trigger=true
            if(questions[stage.question][5]==0){
                stage.score++
            }
        }
        if(mouseX>450*width/800&&mouseX<750*width/800&&mouseY>250*height/550&&mouseY<350*height/550&&!transition.trigger){
            transition.trigger=true
            if(questions[stage.question][5]==1){
                stage.score++
            }
        }
        if(mouseX>50*width/800&&mouseX<350*width/800&&mouseY>400*height/550&&mouseY<500*height/550&&!transition.trigger){
            transition.trigger=true
            if(questions[stage.question][5]==2){
                stage.score++
            }
        }
        if(mouseX>450*width/800&&mouseX<750*width/800&&mouseY>400*height/550&&mouseY<500*height/550&&!transition.trigger){
            transition.trigger=true
            if(questions[stage.question][5]==3){
                stage.score++
            }
        }
    }
}