class particle{
    constructor(layer){
        this.layer=layer
        this.x=random(0,800)
        this.y=-50
        this.vel=0
        this.vel2=random(-1,1)
        this.direction=random(0,360)
        this.remove=false
        this.color=random(0,360)
    }
    display(){
        this.layer.colorMode(HSB,360,255,255,1)
        this.layer.translate(this.x,this.y)
        this.layer.rotate(this.direction)
        this.layer.fill(this.color,255,255)
        this.layer.rect(0,0,10,10)
        this.layer.rotate(-this.direction)
        this.layer.translate(-this.x,-this.y)
        this.layer.colorMode(RGB,255,255,255,1)
    }
    update(){
        this.direction+=5
        this.y+=this.vel
        this.vel+=0.1
        this.x+=this.vel2
        if(this.y>650){
            this.remove=true
        }
    }
}